name: esferapro
description: "Esfera Pro."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  logging: ^1.2.0
  flutter_multi_formatter: ^2.13.0
  fl_chart: ^0.69.0
  flutter_masked_text2: ^0.9.1
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
